### ISSUE TITLE
Allow installation in subfolder

### ISSUE THREAD

**Issue by MartijnOud** [dropcart/dropcart#29]
Currently Dropcart doesn't work if it's not installed in the root of a (sub)domain because of the includes.

**Comment by Dmitrev** [comment]
Fixed in:

https://github.com/Dmitrev/dropcart/commit/902c4834c8b79cbf7eb651b99c9ebe111b5edaf8
https://github.com/Dmitrev/dropcart/commit/a9c70bd4e67fbc35ece326739387a98d15d4f3b1
https://github.com/Dmitrev/dropcart/commit/e96eb5cfa9647260157eaa67e78d4db46cc3eda6
https://github.com/Dmitrev/dropcart/commit/281a6d2b7a5fc5b659e64a32d2c9710b9cd9c49d

**Comment by Dmitrev** [comment]
Assets en redirects zijn nog niet gefixed

**Comment by Dmitrev** [comment]
Fixed, not fully tested!
